development:                                                                    
  adapter: mysql2                                                               
  encoding: utf8                                                                
  collation: utf8_general_ci                                                    
  reconnect: false                                                              
  database: starfire
  pool: 10                                                                      
  username: root                                                                
  password: ""                                                                  
  host: localhost                                                               
  socket: /tmp/mysql.sock                                                       
                                                                                
production:                                                                     
  adapter: mysql2                                                               
  encoding: utf8                                                                
  collation: utf8_general_ci                                                    
  reconnect: false                                                              
  database: starfire
  pool: 10                                                                      
  username: root                                                                
  password: ""                                                                  
  host: localhost           